name: Pylint

on: [push, pull_request, workflow_dispatch]

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # TODO: Print the install script commit hash and Poetry version.
      - name: Install poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/EliahKagan/install.python-poetry.org/ci-repro/pylint-sarif/install-poetry.py |
            python -

      - name: Install project and pylint
        run: poetry install

      - name: Run pylint2sarif (runs pylint)
        run: poetry run pylint2sarif src/*.py

      - name: Upload SARIF to GitHub Security Center
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pylint.sarif
